### ISSUE TITLE
Can't compile build because of spread operator

### ISSUE THREAD

**Issue by iLinn** [sindresorhus/file-type#244] opened 2019-09-09 09:40 UTC
I have faced with issue while trying to build my project, the project uses "@angular/compiler-cli": "4.4.7", with no separate webpack. The build fails on spread operator inside the package:
<img width="660" alt="scn-20190909-122424-xrvbw" src="https://user-images.githubusercontent.com/11552398/64520200-4d2f9180-d2fe-11e9-9afe-3a9ea4b3f5e6.png">

**error text:**
```ERROR in ./node_modules/file-type/index.js
Module parse failed: Unexpected token (29:3)
You may need an appropriate loader to handle this file type.
| 		options = {
| 			offset: 0,
| 			...options
|     };
|     // options = Object.assign({}, options, { offset: 0 });
 @ ./src/app/components/form/services/validation/validation.service.ts 13:15-35
 @ ./src/app/shared/services/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**this works fine for me:**
```
//options = {
//   offset: 0,
//   ...options
//};
options = Object.assign({}, options, { offset: 0 });
```

Node: 10.15.3

**Comment by sindresorhus** [comment] 2019-09-09 10:15
Duplicate of #235

**Closed by sindresorhus** 2019-09-09 10:15 UTC
