### ISSUE TITLE
Not running in browser (uses node's Buffer)

### ISSUE THREAD

**Issue by sbalko** [sindresorhus/file-type#372] opened 2020-06-10 06:22 UTC
Thanks for creating this library! I've been trying to use it in a client-side setting, referencing the "/browser.js" package in an Angular build. It seems like it's using node's Buffer prototype, which does not exist on the client-side web.

**Comment by sindresorhus** [comment] 2020-06-10 06:42
Duplicate of #354

**Closed by sindresorhus** 2020-06-10 06:42 UTC
