### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by skorotkiewicz** [sindresorhus/file-type#235] opened 2019-08-23 03:44 UTC
```
/home/developing/tifu/tifu.beta/node_modules/file-type/index.js:29
                        ...options
                        ^^^
```

**Comment by sindresorhus** [comment] 2019-08-23 09:23
Duplicate of #70

**Comment by sindresorhus** [comment] 2019-08-23 09:23
(Different error, but same resolution)

**Closed by sindresorhus** 2019-08-23 09:23 UTC

**Comment by skorotkiewicz** [comment] 2019-08-24 14:23
How do I fix this?
