### ISSUE TITLE
Your repository makes the computer slow

### ISSUE THREAD

**Issue by BimoSora** [sindresorhus/file-type#524] opened 2022-01-13 14:37 UTC
I tried on a 510 mb vps ram and the vps log reads 510mb 105%, that means your repository is too heavy to process. How to solve this?
![Screenshot_20220113_214050](https://user-images.githubusercontent.com/16408431/149350052-d727a844-5f00-4372-86c1-d12db0b24578.png)

**Comment by Borewit** [comment] 2022-01-13 16:05
Duplicate of #523

**Closed by Borewit** 2022-01-13 16:05 UTC
