### ISSUE TITLE
Can't make it work in a browser

### ISSUE THREAD

**Issue by EvgeniyTT** [sindresorhus/file-type#359] opened 2020-05-12 16:10 UTC
Hello,

I see there are a lot of daily downloads and just a few issues in this package and it looks cool, but I can't manage to make it work in my app. Looks like I miss something basic, but very important. I would greatly appreciate it if you can take a look at the [question I left in stackowerflow](https://stackoverflow.com/questions/61751782/different-errors-using-the-file-type-package-in-a-browser-angular) and tell me what I'm doing wrong.

I have an Angular app and a component where I upload files. Now I want to check a real file's type using the `file-type` library.
I took the basic example of checking a file type from BLOB:

```
const FileType = require('file-type/browser');

(async () => {
    const blob = new Blob(['<?xml version="1.0" encoding="ISO-8859-1" ?>'], {
        type: 'plain/text',
        endings: 'native'
    });

    console.log(await FileType.fromBlob(blob));
    //=> {ext: 'txt', mime: 'plain/text'}
})();
```
but it gives me an error:

> Error in C:/project/node_modules/readable-web-to-node-stream/lib/index.js
> Module not found: Error: can't resolve 'stream' in C:/project/node_modules/readable-web-to-node-stream/lib/

I've added a stream package (what is not a good solution, probably), and the error was changed to:

> Uncaught TypeError: Class extends value undefined is not a constructor or null

After that, I decided that might be my current project is too complicated and I can give it a shot in a new small project, so I created one. Installed file-type and took the same example from their page (I only changed const FileType = require('file-type/browser'); to import {fromBlob} from 'file-type/browser');

But here another error appears:

> Uncaught ReferenceError: global is not defined

I added (window as any)['global'] = window; to the polyfill.js

> Uncaught ReferenceError: Buffer is not defined

I added the buffer package and global.Buffer = global.Buffer || require('buffer').Buffer; to the polyfill.js

> Uncaught ReferenceError: process is not defined

Here I gave up. I definitely don't understand something and need some help. What I missed?

Wanted to add a [stackblitz example](https://stackblitz.com/edit/angular-ivy-gl8au3), but it gives me another error:

> Import error, can't find file: ./common

Thanks in advance

**Comment by sindresorhus** [comment] 2020-05-12 17:46
Duplicate of #354

**Closed by sindresorhus** 2020-05-12 17:46 UTC
