### ISSUE TITLE
file type of .xlsx is coming as application/x-msi

### ISSUE THREAD

**Issue by shah20** [sindresorhus/file-type#395] opened 2020-09-15 03:26 UTC

**Comment by Borewit** [comment] 2020-09-15 05:58
@shah20 Maybe I was not clear enough in #394. I suggest you spend some energy yourself, looking into the issue, before bothering us. If you do believe creating a ticker is justified, you provide proper description, sample file, version number and everything what could be useful to us to make our life easy. 

I don't think your version is up to date, duplicate of #377.

**Closed by Borewit** 2020-09-15 05:58 UTC
