### ISSUE TITLE
Changes on typing break with `stream.Readable`

### ISSUE THREAD

**Issue by ajotaos** [sindresorhus/file-type#675] opened 2024-09-21 13:15 UTC
### Description

It seems an update of a type library dependency where the input types for `fileTypeFromStream` come from, no longer allow to pass `stream.Readable`. This is the error I'm receiving:

```
Argument of type 'Readable' is not assignable to parameter of type 'AnyWebByteStream'.
  Type 'ReadableBase' is missing the following properties from type 'ReadableStream<Uint8Array>': locked, cancel, getReader, pipeThrough, and 3 more.ts(2345)
```

I would need to use `Readable.toWeb` to accommodate the typing but the library would crash with:

```
The argument 'stream' must be a byte stream. Received ReadableStream { locked: false, state: 'reada
ble', supportsBYOB: false }
```

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [X] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by Borewit** [comment] 2024-09-24 14:16
It looks like you `stream.Readable` is not recognized as an instance of [stream.Readable](https://nodejs.org/api/stream.html#class-streamreadable) and hence the (wrong) assumption is made you passed a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream).

Can you give more details @ajotaos:
- Which JavaScript engine are you using, and which version?
- Where does the [stream.Readable](https://nodejs.org/api/stream.html#class-streamreadable) instance come from, how was is created / derived?
- Can you create a repository reproducing the issue?

**Comment by ajotaos** [comment] 2024-09-25 01:09
I'm using regular Node.js v20.

The stream comes from the AWS S3 library GetObject Output although the same result occurs for any readable instance I'm creating, even with `const readable = new stream.Readable();`

Also, I'm using typescript to type the input using `import type { Readable } from 'node:stream'`.

The ReadableStream I mentioned it's because that's what the type system is requiring me to pass to silence the type error but leads to a runtime error.

It's a codebase I have from work but the non-confidential portion of it goes like:

```
import { fileTypeFromStream } from 'file-type';

import type { Readable } from 'node:stream';

async function getMimeTypeFromStream(body: Readable) {
	const fileType = await fileTypeFromStream(body);
	return fileType?.mime ?? 'application/octet-stream';
}

```

Using:

`"type-fest": "^4.21.0"`

**Comment by Borewit** [comment] 2024-09-25 18:12
Works just fine on my end:

`node -v` ➡️  `v20.17.0`

```js
import { fileTypeFromStream } from 'file-type';
import * as stream from 'node:stream';

async function getMimeTypeFromStream(body) {
  const fileType = await fileTypeFromStream(body);
  return fileType?.mime ?? 'application/octet-stream';
}

// Create a custom Readable stream
const readable = new stream.Readable({
  read() {
    // Push some binary data (for example, a PNG file signature)
    this.push(Buffer.from([0x47, 0x49, 0x46]));
    // No more data
    this.push(null);
  }
});

// Get the mime type from the stream
(async () => {
  const result = await getMimeTypeFromStream(readable);
  console.log(result); // Expected output: "image/png"
})();
```
➡️  `image/gif` ✅

**Comment by ajotaos** [comment] 2024-09-26 19:29
I'm talking about the type signature not allowing `stream.Readable` to be passed to `fileTypeFromStream`. The implementation allows it, but Typescript does not.

![Screenshot 2024-09-26 at 2 29 08 PM](https://github.com/user-attachments/assets/3f31a858-2283-4eac-a04e-69e435df7f10)

**Comment by Borewit** [comment] 2024-09-27 09:23
Works fine with TypeScript for me as well:

```ts
import { fileTypeFromStream } from 'file-type';
import { Readable } from 'node:stream';

async function getMimeTypeFromStream(body: Readable) {
    const fileType = await fileTypeFromStream(body);
    return fileType?.mime ?? 'application/octet-stream';
}

// Create a custom Readable stream
const readable = new Readable({
    read() {
        // Push some binary data (for example, a PNG file signature)
        this.push(Buffer.from([0x47, 0x49, 0x46]));
        // No more data
        this.push(null);
    }
});

// Get the mime type from the stream
(async () => {
    const result = await getMimeTypeFromStream(readable);
    console.log(result); // Expected output: "image/gif"
})();
```

Repo: https://github.com/Borewit/file-type-example/blob/master/ts-esm/test-readable.ts

**Comment by ajotaos** [comment] 2024-09-27 19:03
The typing of `fileTypeFromStream` in your current latest release has this signature:

```
import type { AnyWebByteStream } from 'strtok3';
export function fileTypeFromStream(stream: AnyWebByteStream): Promise<FileTypeResult | undefined>;
```
Source: https://github.com/Borewit/strtok3/blob/e7c32adb7fa2e25735cb3ff3f8f39943a635a047/lib/core.ts#L8

`strtok3.AnyWebByteStream` is a re-export from the `peek-readable` library.

```
export { type AnyWebByteStream } from 'peek-readable';
```
Source: https://github.com/Borewit/strtok3/blob/e7c32adb7fa2e25735cb3ff3f8f39943a635a047/lib/core.ts#L8


And `peek-readable. AnyWebByteStream` has the signature:

```
import type { ReadableStream as NodeReadableStream } from 'node:stream/web';

export type AnyWebByteStream = NodeReadableStream<Uint8Array> | ReadableStream<Uint8Array>;
```

Source: https://github.com/Borewit/peek-readable/blob/b2fa00f40c0df4732208e107dcc2dca760cb22dc/lib/WebStreamReader.ts#L6

In this signature, `node:stream.Readable` does match that condition.

**Comment by Borewit** [comment] 2024-09-28 10:00
This is the applicable declaration::

https://github.com/sindresorhus/file-type/blob/0e91f7be09fbe7f1ac3928d96b7a23b611532d52/index.d.ts#L59

where `NodeReadableStream` is exactly the type you are looking for:

https://github.com/sindresorhus/file-type/blob/0e91f7be09fbe7f1ac3928d96b7a23b611532d52/index.d.ts#L5

Note that these typing are only available via the Node.specific entry point, as the `node:stream` is a Node specific dependency.

**Comment by Crauzer** [comment] 2024-10-06 10:05
I have the same issue as @ajotaos above. I'm trying to verify the file type of a file being uploaded in a Remix JS upload handler. The data itself is `AsyncIterable<Uint8Array>` that gets converted into a node `Readable`

![image](https://github.com/user-attachments/assets/1ee10bdf-ddb8-42a2-a92b-73d835853f63)

**Comment by Borewit** [comment] 2024-10-06 11:21
> I have the same issue as @ajotaos above. I'm trying to verify the file type of a file being uploaded in a Remix JS upload handler. The data itself is AsyncIterable<Uint8Array> that gets converted into a node Readable

@Crauzer , if you want to use the Node.js specific functions, you should import this module with Node.js. Using Remix that means you need import file-type on the **server-side**, if you import the module on the client side, only the default (non Node.js) functions are available. If that does not work, you should raise an issue at Remix.

**Comment by Borewit** [comment] 2024-10-12 11:43
I close this issue under the assumption it is resolves, otherwise you may re-open.

**Closed by Borewit** 2024-10-12 11:43 UTC
Labels: cannot reproduce
