### ISSUE TITLE
On IE11 there is no method findIndex

### ISSUE THREAD

**Issue by frankred** [sindresorhus/file-type#145] opened 2018-06-26 11:48 UTC
Checking the file type of a .xlsx file on IE11 will cause the following error:

`SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "findIndex" nicht`

In English: "findIndex" method is not available.

**Comment by sindresorhus** [comment] 2018-06-26 16:14
Duplicate of #70

**Closed by sindresorhus** 2018-06-26 16:14 UTC

**Comment by frankred** [comment] 2018-06-26 18:52
This is very pity :( By just replacing this method with a polyfill method with 5 lines of code would make the lib completely workable and compatible in IE11. You do not have to adjust the build process and build some complex polyfill stuff. Just add this code to your library and use findIndex2 instead:

```
Array.prototype.findIndex2 = function(predicate, thisArg) {
      if (this === null) {
          throw new TypeError('Cannot read property \'findIndex\' of null');
      }
  
      if (typeof predicate !== "function") {
          throw new TypeError(typeof predicate + ' is not a function');
      }
  
      var arrLength = this.length;
      var index = -1;
  
      for (var i = 0; i < arrLength; i++) {
          if (predicate.call(thisArg, this[i], i, this)) {
              index = i;
              break;
          }
      }
  
      return index;
  };

```

If you do not want a prototype I can make also a const method to use this. Btw: findIndex2 is faster then the native implementation (with my setup).

**Comment by mifi** [comment] 2018-06-26 19:16
More code leads to harder maintenance, and every library developer cannot be burdened with supporting every ancient browser. There is already excellent tooling for that.
