### ISSUE TITLE
Cannot find module 'strtok3/core'

### ISSUE THREAD

**Issue by kryopix** [sindresorhus/file-type#539] opened 2022-04-19 12:17 UTC
Hi, 

i have found this related closed merge Request https://github.com/sindresorhus/file-type/pull/513 but i have this error still in the latest version.

Unfortunately, you won't get any more answers to questions in this thread. When is it possible to release the next version where this problem is fixed?

**Comment by m4cn4ir** [comment] 2022-04-28 10:10
I am having this issue as well, rendering file-type, unfortunately, unusable at the moment. Fix seems easy though? Just fix the import statement of strtok3.
Anyways, I found a good alternative with: https://github.com/LarsKoelpin/magic-bytes

**Comment by sindresorhus** [comment] 2022-05-27 09:27
Duplicate of #541

**Closed by sindresorhus** 2022-05-27 09:27 UTC
