### ISSUE TITLE
more format need to be added

### ISSUE THREAD

**Issue by akshaybhuradia2020** [sindresorhus/file-type#382] opened 2020-07-28 17:16 UTC
Following are the list for extension 

list = ['gsm', 'au', 'aiff', 'caf', 'vox', 'mpc',
            'mpp', 'wvc', 'raw', 'wav', 'ra', 'mka',
 'ram', 'dss', 'msv', 'dvf', 'oma', 'omg',
 'atp', 'tiff', 'dxf', 'ai']

any idea how to tackle this format list = ['txt', 'csv', 'svg', 'xls', 'html', 'htm', 'ppt', 'doc']

**Comment by bencmbrook** [comment] 2020-07-28 18:52
Hello @akshaybhuradia2020 — can you please add more detail to the issue?

I suspect this is a duplicate of these issues, so I'll close this out unless there is a separate request:
- https://github.com/sindresorhus/file-type/issues/376
- https://github.com/sindresorhus/file-type/issues/32
- https://github.com/sindresorhus/file-type/issues/264

**Closed by bencmbrook** 2020-07-28 18:52 UTC

**Comment by akshaybhuradia2020** [comment] 2020-07-29 09:44
@bencmbrook 

What about for this list.
Following are the list of extension

**list = ['gsm', 'au', 'aiff', 'caf', 'vox', 'mpc',
'mpp', 'wvc', 'raw', 'wav', 'ra', 'mka',
'ram', 'dss', 'msv', 'dvf', 'oma', 'omg',
'atp', 'tiff', 'dxf', 'ai']**

 
**These extension supports are not given in documentation**

**Comment by Borewit** [comment] 2020-07-29 10:24
What about you are doing a little research yourself @akshaybhuradia2020?
