### ISSUE TITLE
README is faulty

### ISSUE THREAD

**Issue by bertmeeuws** [sindresorhus/file-type#500] opened 2021-11-24 13:52 UTC
Your readme mentions "import {fileTypeFromBuffer} from 'file-type'".
But it's actually "import {fromBuffer} from 'file-type'".

**Comment by sindresorhus** [comment] 2021-11-24 17:26
Duplicate of #484

**Comment by sindresorhus** [comment] 2021-11-24 17:26
However, the new release is out: https://github.com/sindresorhus/file-type/releases/tag/v17.0.0

**Closed by sindresorhus** 2021-11-24 17:26 UTC
