### ISSUE TITLE
Publish to npm with transpiled file

### ISSUE THREAD

**Issue by RamIdeas** [sindresorhus/file-type#95] opened 2017-06-21 15:31 UTC
Is it possible to publish an "index.es5.js" which is already transpiled?

I currently have to add an exception to my webpack config file to skip all files in `node_modules` _except `node_modules/file-type`_

```diff
- { test: /\.js$/, use: ['babel-loader'], exclude: /node_modules\/(?!@mendeley)/ },
+ { test: /\.js$/, use: ['babel-loader'], exclude: /node_modules\/(?!@mendeley|file-type)/ },
```

If an `index.es5.js` was included as well as `index.js` I could simply `require('file-type/index.es5')` or `import 'file-type/index.es5`

```diff
- const fileType = require('file-type');
+ const fileType = require('file-type/index.es5');

- import fileType from 'file-type'
+ import fileType from 'file-type/index.es5'
```

**Comment by sindresorhus** [comment] 2017-06-21 15:53
Duplicate of https://github.com/sindresorhus/file-type/issues/70.

**Closed by sindresorhus** 2017-06-21 15:53 UTC
