### ISSUE TITLE
audio/mpeg detected as video/webm or video/mp4

### ISSUE THREAD

**Issue by bramvbilsen** [sindresorhus/file-type#599] opened 2023-05-16 18:24 UTC
Very similar to this issue https://github.com/sindresorhus/file-type/issues/488. 

I am using the MediaRecorder API to record audio in the `audio/mpeg` format. Upon checking the mimetype using `file-type`, I get either `video/mp4` on Safari and `video/webm` on all other browsers.  

As I do not support video uploads, it is an easy workaround. But a workaround nonetheless.
Is this something others can reproduce as well?

**Comment by Borewit** [comment] 2023-11-10 23:02
I close the issue as this cannot be reproduced.

**Closed by Borewit** 2023-11-10 23:02 UTC
Labels: cannot reproduce

**Comment by ThePendulum** [comment] 2023-12-12 23:47
Same issue here. I initially thought it had to do with using 16.5.4 for CommonJS compatability, but 18.x still seems to identify them as `video/webm` [chrome.webm](https://github.com/sindresorhus/file-type/assets/973976/983f9be6-44f3-4b08-b030-340f2dd7fbf7)
[firefox.webm](https://github.com/sindresorhus/file-type/assets/973976/89d7d25a-6cf9-4baa-a3df-adf94dd5d7ac).

The [Magic-Bytes.js demo](https://larskoelpin.github.io/magic-bytes/) does come up with `audio/webm`, but instead of `video/webm`, it seems to be struggling to distinguish it from a Matroska file instead.

This is the code I used to record it:

```
navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
    let chunks = [];

    mediaRecorder.value = new MediaRecorder(stream, {
        mimeType: 'audio/webm',
    });

    mediaRecorder.value.addEventListener('dataavailable', (event) => chunks.push(event.data));

    mediaRecorder.value.addEventListener('stop', () => {
        const blob = new Blob(chunks, { type: 'audio/webm' });
        const audioUrl = URL.createObjectURL(blob);

        console.log(audioUrl); // save or set as player src

        chunks = [];
    });
});
```
