### ISSUE TITLE
Publish pre-compiled package

### ISSUE THREAD

**Issue by marin-liovic** [sindresorhus/file-type#134] opened 2018-03-29 13:06 UTC
This package cannot be used with create-react-app because minification fails. See here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Can you please compile this code to ES5 before publishing to NPM?

**Comment by sindresorhus** [comment] 2018-03-29 13:48
Duplicate of #130

**Closed by sindresorhus** 2018-03-29 13:48 UTC
