### ISSUE TITLE
v4 upgrade (usage of =>) breaks easy browserify support

### ISSUE THREAD

**Issue by shamasis** [sindresorhus/file-type#78] opened 2017-03-21 12:33 UTC
Hi,

The v4 release does a great job to move on to using `=>` in code. However, simple browserify fails now. I understand that browserify of this module is odd, but we do it. :-)

Simply adding `babel` transform in package will make this way way easier for consumption. The other alternative for browserify consumers is to use complicated logic to specifically transform this module.

```
"browserify": {
    "transform": [["babelify", { "presets": ["latest"] }]]
  }
```
is all what we mere mortals need @sindresorhus

**Comment by sindresorhus** [comment] 2017-03-21 13:18
As I commented, duplicate of https://github.com/sindresorhus/file-type/issues/70. I'm not interested in doing anything special for the browser. Please read: https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491 Sorry.

You could always just stay on v3. It has the most common formats you'll need.

**Closed by sindresorhus** 2017-03-21 13:18 UTC

**Comment by pconerly** [comment] 2017-06-12 20:50
My team uses webpack, and we babel everything except `node_modules`. We ended up using this regex in our `exclude` so that we babel file-type, but continue to exclude all other node_modules.

```
/node_modules(?!.*\/file-type\/).*/
```

https://regex101.com/r/fUZJlR/5/tests

**Comment by philipstanislaus** [comment] 2017-10-04 07:08
I had a similar issue. Instead of complicating my build chains, I forked this repository, added an es5 build and published it to npm: 

https://www.npmjs.com/package/file-type-es5

I will keep the repository in sync. Thanks to @sindresorhus for this awesome library!
