### ISSUE TITLE
Error when trying to import/use in svelte/rollup project.

### ISSUE THREAD

**Issue by iohzrd** [sindresorhus/file-type#538] opened 2022-03-16 00:05 UTC
When I import it how the doc suggests.
```import { fileTypeFromBuffer } from "file-type";```
I get:
```
[!] (plugin svelte) Error: No such built-in module: node:buffer/package.json
Error: No such built-in module: node:buffer/package.json
    at new NodeError (node:internal/errors:372:5)
    at Function.Module._load (node:internal/modules/cjs/loader:785:13)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.resolveId (/home/iohzrd/src/identia/node_modules/rollup-plugin-svelte/index.js:67:11)
    at /home/iohzrd/src/identia/node_modules/rollup/dist/shared/rollup.js:22779:37
```

I've also tried importing it like so:
```import { fileTypeFromBuffer } from "file-type/index";```
As is often necessary in svelte.
But then I get:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
file-type/index (imported by src/components/Post.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
file-type/index (guessing 'index$5')
```

I tried various solutions related to external dependencies but still couldn't get it to work.
Keep in mind that the code works otherwise.
Anyone have any insights?

**Comment by sindresorhus** [comment] 2022-03-16 05:45
Duplicate of #525

**Comment by sindresorhus** [comment] 2022-03-16 05:45
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Closed by sindresorhus** 2022-03-16 05:45 UTC
