### ISSUE TITLE
Mime type : text/csv is not supported by fileType.fromBuffer() method

### ISSUE THREAD

**Issue by mansu1101** [sindresorhus/file-type#371] opened 2020-06-08 07:48 UTC
I want to use this module in my project to check the file type based on buffer data. But when I tried to load csv buffer it's not giving me FileTypeResult result.
Can you guys please update this type also.

the extension is: csv
MimeType: text/csv
![mimetypesupport](https://user-images.githubusercontent.com/16834658/84005260-78790700-a98a-11ea-87f2-0b88d6e5279c.png)

**Comment by sindresorhus** [comment] 2020-06-08 08:01
Duplicate of #264

**Comment by sindresorhus** [comment] 2020-06-08 08:02
Also in the readme:

> The following file types will not be accepted:
> .csv - [Reason.](https://github.com/sindresorhus/file-type/issues/264#issuecomment-568439196)

**Closed by sindresorhus** 2020-06-08 08:01 UTC
